package fun.derjxnnik.misc;

import org.bukkit.ChatColor;

public class Colors {
   public static final String BLACK;
   public static final String DARK_BLUE;
   public static final String DARK_GREEN;
   public static final String DARK_AQUA;
   public static final String DARK_RED;
   public static final String DARK_PURPLE;
   public static final String GOLD;
   public static final String GRAY;
   public static final String DARK_GRAY;
   public static final String BLUE;
   public static final String GREEN;
   public static final String AQUA;
   public static final String RED;
   public static final String LIGHT_PURPLE;
   public static final String YELLOW;
   public static final String WHITE;
   public static final String END_YELLOW;
   public static final String BOLD_BLACK;
   public static final String BOLD_DARK_BLUE;
   public static final String BOLD_DARK_GREEN;
   public static final String BOLD_DARK_AQUA;
   public static final String BOLD_DARK_RED;
   public static final String BOLD_DARK_PURPLE;
   public static final String BOLD_GOLD;
   public static final String BOLD_GRAY;
   public static final String BOLD_DARK_GRAY;
   public static final String BOLD_BLUE;
   public static final String BOLD_GREEN;
   public static final String BOLD_AQUA;
   public static final String BOLD_RED;
   public static final String BOLD_LIGHT_PURPLE;
   public static final String BOLD_YELLOW;
   public static final String BOLD_WHITE;
   public static final String BOLD;
   public static final String ITALIC;
   public static final String UNDERLINE;
   public static final String STRIKETHROUGH;
   public static final String RESET;
   public static final String PREFIX;
   public static final String CONSOLE_SENDER;
   public static final String NO_PERMS;
   public static final String DISABLED;

   public static String strip(String text) {
      return ChatColor.stripColor(text);
   }

   static {
      BLACK = ChatColor.BLACK.toString();
      DARK_BLUE = ChatColor.DARK_BLUE.toString();
      DARK_GREEN = ChatColor.DARK_GREEN.toString();
      DARK_AQUA = ChatColor.DARK_AQUA.toString();
      DARK_RED = ChatColor.DARK_RED.toString();
      DARK_PURPLE = ChatColor.DARK_PURPLE.toString();
      GOLD = ChatColor.GOLD.toString();
      GRAY = ChatColor.GRAY.toString();
      DARK_GRAY = ChatColor.DARK_GRAY.toString();
      BLUE = ChatColor.BLUE.toString();
      GREEN = ChatColor.GREEN.toString();
      AQUA = ChatColor.AQUA.toString();
      RED = ChatColor.RED.toString();
      LIGHT_PURPLE = ChatColor.LIGHT_PURPLE.toString();
      YELLOW = ChatColor.YELLOW.toString();
      WHITE = ChatColor.WHITE.toString();
      END_YELLOW = net.md_5.bungee.api.ChatColor.of("#e6edae").toString();
      String var10000 = String.valueOf(ChatColor.BLACK);
      BOLD_BLACK = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.DARK_BLUE);
      BOLD_DARK_BLUE = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.DARK_GREEN);
      BOLD_DARK_GREEN = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.DARK_AQUA);
      BOLD_DARK_AQUA = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.DARK_RED);
      BOLD_DARK_RED = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.DARK_PURPLE);
      BOLD_DARK_PURPLE = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.GOLD);
      BOLD_GOLD = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.GRAY);
      BOLD_GRAY = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.DARK_GRAY);
      BOLD_DARK_GRAY = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.BLUE);
      BOLD_BLUE = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.GREEN);
      BOLD_GREEN = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.AQUA);
      BOLD_AQUA = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.RED);
      BOLD_RED = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.LIGHT_PURPLE);
      BOLD_LIGHT_PURPLE = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.YELLOW);
      BOLD_YELLOW = var10000 + String.valueOf(ChatColor.BOLD);
      var10000 = String.valueOf(ChatColor.WHITE);
      BOLD_WHITE = var10000 + String.valueOf(ChatColor.BOLD);
      BOLD = ChatColor.BOLD.toString();
      ITALIC = ChatColor.ITALIC.toString();
      UNDERLINE = ChatColor.UNDERLINE.toString();
      STRIKETHROUGH = ChatColor.STRIKETHROUGH.toString();
      RESET = ChatColor.RESET.toString();
      PREFIX = GRAY + "[" + BOLD_BLUE + "SMP" + GRAY + "] " + RESET;
      CONSOLE_SENDER = PREFIX + RED + "Only players are allowed to use this command.\nPlease contact the devs if you believe this is a mistake.";
      NO_PERMS = PREFIX + RED + "You don't have permission to use this command.";
      DISABLED = PREFIX + RED + "This command is currently disabled.\nPlease contact the devs if you believe that this is an error.";
   }
}
